/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankingsIndexRouteImport } from './routes/rankings.index'
import { Route as RankingsPersonalRouteImport } from './routes/rankings.personal'
import { Route as CustomResultsRouteImport } from './routes/custom.results'
import { Route as CompetitionIdRouteImport } from './routes/competition.$id'
import { Route as RankingsPersonalIdRouteImport } from './routes/rankings.personal.$id'
import { Route as CompetitionIdResultsRouteImport } from './routes/competition.$id.results'

const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsPersonalRoute = RankingsPersonalRouteImport.update({
  id: '/rankings/personal',
  path: '/rankings/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomResultsRoute = CustomResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => CustomRoute,
} as any)
const CompetitionIdRoute = CompetitionIdRouteImport.update({
  id: '/competition/$id',
  path: '/competition/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsPersonalIdRoute = RankingsPersonalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RankingsPersonalRoute,
} as any)
const CompetitionIdResultsRoute = CompetitionIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => CompetitionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom': typeof CustomRouteWithChildren
  '/competition/$id': typeof CompetitionIdRouteWithChildren
  '/custom/results': typeof CustomResultsRoute
  '/rankings/personal': typeof RankingsPersonalRouteWithChildren
  '/rankings': typeof RankingsIndexRoute
  '/competition/$id/results': typeof CompetitionIdResultsRoute
  '/rankings/personal/$id': typeof RankingsPersonalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom': typeof CustomRouteWithChildren
  '/competition/$id': typeof CompetitionIdRouteWithChildren
  '/custom/results': typeof CustomResultsRoute
  '/rankings/personal': typeof RankingsPersonalRouteWithChildren
  '/rankings': typeof RankingsIndexRoute
  '/competition/$id/results': typeof CompetitionIdResultsRoute
  '/rankings/personal/$id': typeof RankingsPersonalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom': typeof CustomRouteWithChildren
  '/competition/$id': typeof CompetitionIdRouteWithChildren
  '/custom/results': typeof CustomResultsRoute
  '/rankings/personal': typeof RankingsPersonalRouteWithChildren
  '/rankings/': typeof RankingsIndexRoute
  '/competition/$id/results': typeof CompetitionIdResultsRoute
  '/rankings/personal/$id': typeof RankingsPersonalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom'
    | '/competition/$id'
    | '/custom/results'
    | '/rankings/personal'
    | '/rankings'
    | '/competition/$id/results'
    | '/rankings/personal/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom'
    | '/competition/$id'
    | '/custom/results'
    | '/rankings/personal'
    | '/rankings'
    | '/competition/$id/results'
    | '/rankings/personal/$id'
  id:
    | '__root__'
    | '/'
    | '/custom'
    | '/competition/$id'
    | '/custom/results'
    | '/rankings/personal'
    | '/rankings/'
    | '/competition/$id/results'
    | '/rankings/personal/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomRoute: typeof CustomRouteWithChildren
  CompetitionIdRoute: typeof CompetitionIdRouteWithChildren
  RankingsPersonalRoute: typeof RankingsPersonalRouteWithChildren
  RankingsIndexRoute: typeof RankingsIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/personal': {
      id: '/rankings/personal'
      path: '/rankings/personal'
      fullPath: '/rankings/personal'
      preLoaderRoute: typeof RankingsPersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/results': {
      id: '/custom/results'
      path: '/results'
      fullPath: '/custom/results'
      preLoaderRoute: typeof CustomResultsRouteImport
      parentRoute: typeof CustomRoute
    }
    '/competition/$id': {
      id: '/competition/$id'
      path: '/competition/$id'
      fullPath: '/competition/$id'
      preLoaderRoute: typeof CompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/personal/$id': {
      id: '/rankings/personal/$id'
      path: '/$id'
      fullPath: '/rankings/personal/$id'
      preLoaderRoute: typeof RankingsPersonalIdRouteImport
      parentRoute: typeof RankingsPersonalRoute
    }
    '/competition/$id/results': {
      id: '/competition/$id/results'
      path: '/results'
      fullPath: '/competition/$id/results'
      preLoaderRoute: typeof CompetitionIdResultsRouteImport
      parentRoute: typeof CompetitionIdRoute
    }
  }
}

interface CustomRouteChildren {
  CustomResultsRoute: typeof CustomResultsRoute
}

const CustomRouteChildren: CustomRouteChildren = {
  CustomResultsRoute: CustomResultsRoute,
}

const CustomRouteWithChildren =
  CustomRoute._addFileChildren(CustomRouteChildren)

interface CompetitionIdRouteChildren {
  CompetitionIdResultsRoute: typeof CompetitionIdResultsRoute
}

const CompetitionIdRouteChildren: CompetitionIdRouteChildren = {
  CompetitionIdResultsRoute: CompetitionIdResultsRoute,
}

const CompetitionIdRouteWithChildren = CompetitionIdRoute._addFileChildren(
  CompetitionIdRouteChildren,
)

interface RankingsPersonalRouteChildren {
  RankingsPersonalIdRoute: typeof RankingsPersonalIdRoute
}

const RankingsPersonalRouteChildren: RankingsPersonalRouteChildren = {
  RankingsPersonalIdRoute: RankingsPersonalIdRoute,
}

const RankingsPersonalRouteWithChildren =
  RankingsPersonalRoute._addFileChildren(RankingsPersonalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomRoute: CustomRouteWithChildren,
  CompetitionIdRoute: CompetitionIdRouteWithChildren,
  RankingsPersonalRoute: RankingsPersonalRouteWithChildren,
  RankingsIndexRoute: RankingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
