# 1. Required to use advanced import sorting features
unstable_features = true

# 2. Merge imports from the same module (e.g., Crate, Module, Item)
imports_granularity = "Module"

# 3. Group imports into sections: Std lib, external crates, and local modules
group_imports = "StdExternalCrate"